/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./public/index.html",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#acedff",
        "error": "#ffb4ab",
        "surface-container-low": "#001a42",
        "tertiary-fixed-dim": "#4cd7f6",
        "secondary-fixed": "#f0dbff",
        "inverse-primary": "#124af0",
        "on-surface-variant": "#c4c5d9",
        "on-primary-fixed": "#001356",
        "on-secondary-container": "#d6a9ff",
        "on-tertiary": "#003640",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-secondary-fixed": "#2c0051",
        "on-tertiary-fixed-variant": "#004e5c",
        "inverse-surface": "#d8e2ff",
        "surface-container-high": "#112952",
        "surface-dim": "#001232",
        "on-primary-fixed-variant": "#0035be",
        "surface-container-lowest": "#000d28",
        "surface-container": "#031e47",
        "on-secondary": "#490080",
        "inverse-on-surface": "#192f59",
        "primary-fixed-dim": "#b8c3ff",
        "primary-fixed": "#dde1ff",
        "tertiary-container": "#00788c",
        "primary-container": "#2e5bff",
        "on-primary": "#002388",
        "outline-variant": "#434656",
        "background": "#001232",
        "surface-variant": "#1e345d",
        "on-tertiary-fixed": "#001f26",
        "secondary-container": "#6f00be",
        "on-surface": "#d8e2ff",
        "on-secondary-fixed-variant": "#6900b3",
        "primary": "#b8c3ff",
        "outline": "#8e90a2",
        "surface-bright": "#223862",
        "on-primary-container": "#efefff",
        "secondary": "#ddb7ff",
        "surface": "#001232",
        "surface-container-highest": "#1e345d",
        "surface-tint": "#b8c3ff",
        "secondary-fixed-dim": "#ddb7ff",
        "on-error-container": "#ffdad6",
        "tertiary": "#4cd7f6",
        "on-background": "#d8e2ff",
        "on-tertiary-container": "#d7f6ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-md": "16px",
        "stack-lg": "32px",
        "stack-sm": "8px",
        "container-max": "1280px",
        "section-padding": "120px",
        "gutter": "32px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "display-lg": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "label-md": ["JetBrains Mono"],
        "headline-lg": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"]
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["72px", { lineHeight: "80px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["36px", { lineHeight: "44px", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
